"""Load the Step 3 product catalog and provide lookup helpers.

``product_catalog.json`` is generated by ``build_catalog.py`` from the customer
price list. It maps product families -> models -> {list price, cost, margin}
per currency. The web layer serves this to the margin calculator so the user
can pick a family, then a model, and have the price/cost auto-filled.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

CATALOG_PATH = Path(__file__).resolve().parent / "product_catalog.json"


@lru_cache(maxsize=1)
def load_catalog() -> dict:
    """Load and cache the catalog. Returns an empty catalog if missing."""
    try:
        return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"source": "", "currencies": ["GBP", "EUR", "USD"], "families": []}


def families() -> list[dict]:
    """Lightweight family list (id, name, model count) for dropdowns."""
    return [
        {"id": f.get("id"), "name": f.get("name"), "modelCount": f.get("modelCount", len(f.get("models", [])))}
        for f in load_catalog().get("families", [])
    ]


def find_model(family_id: str, model: str) -> dict | None:
    """Return a model record by family id + model name (exact match)."""
    for f in load_catalog().get("families", []):
        if f.get("id") != family_id:
            continue
        for m in f.get("models", []):
            if m.get("model") == model:
                return m
    return None
